pub const GENDER_MALE: [&str; 150] = [
    "Mittens", "Whiskers", "Shadow", "Smokey", "Tiger",
    "Oreo", "Simba", "Ginger", "Felix", "Jack", "Jasper",
    "Leo", "Loki", "Lucky", "Max", "Milo", "Chamallow",
    "Oscar", "Peanut", "Rocky", "Surf", "Midnight", "Storm",
    "Ash", "Bandit", "Boots", "Casper", "Cinnamon", "Coco",
    "Comet", "Cosmo", "Diesel", "Dusty", "Elvis", "Fudge",
    "Gizmo", "Marble", "Mochi", "Nugget", "Panda", "Pumpkin",
    "Raven", "Rocco", "Sable", "Toby", "Tux", "Waffles",
    "Yoda", "Zeus", "Ace", "Apollo", "Bamboo", "Bear", "Blaze",
    "Bolt", "Boo", "Buster", "Butterscotch", "Champ", "Chase",
    "Chester", "Chico", "Claw", "Clyde", "Cocoa", "Cricket",
    "Diesel", "Domino", "Draco", "Duke", "Dusty", "Echo",
    "Fang", "Fidget", "Flash", "Fuzz", "Galaxy", "Gatsby",
    "Ghost", "Gizmo", "Goblin", "Goliath", "Gunner", "Hades",
    "Hawk", "Hercules", "Hobbes", "Hopper", "Hunter", "Iggy",
    "Inky", "Jaguar", "Jax", "Jet", "Karma", "Koda", "Kona",
    "Lynx", "Magma", "Maverick", "Merlin", "Mojo", "Nero",
    "Ninja", "Noodle", "Obi", "Onyx", "Ozzie", "Patch", "Phoenix",
    "Pippin", "Pirate", "Poe", "Quasar", "Quincy", "Ranger",
    "Rebel", "Reggie", "Rex", "Rocket", "Rusty", "Saber",
    "Scooter", "Scout", "Shadow", "Shiloh", "Skipper", "Slate",
    "Smudge", "Snickers", "Socks", "Spike", "Sprout", "Stitch",
    "Stripe", "Taco", "Thumper", "Tigger", "Timber", "Toto",
    "Tsunami", "Turbo", "Twix", "Vader", "Whisker", "Wolf",
    "Wombat", "Wrigley", "Yeti", "Ziggy"
];

pub const GENDER_FEMALE: [&str; 168] = [
    "Fluffy", "Luna", "Suzie", "Princess", "Marelle", "Bella",
    "Chloe", "Coco", "Daisy", "Nyx", "Dinah", "Nala", "Pepper",
    "Zoe", "Callie", "Angel", "Kitty", "Willow", "Sassy",
    "Patches", "Tinkerbell", "Twilight", "Buttercup", "Caramel",
    "Cupcake", "Ebony", "Echo", "Fawn", "Fifi", "Galaxy",
    "Harmony", "Jinx", "Kiwi", "Lady", "Licorice", "Maple",
    "Misty", "Mocha", "Mystery", "Opal", "Pearl", "Pebbles",
    "Pippa", "Skittles", "Snowball", "Sundae", "Acorn", "Amber",
    "Amethyst", "Aqua", "Autumn", "Bambi", "Beetle", "Berry",
    "Biscuit", "Blossom", "Blue", "Bonbon", "Breeze", "Bubbles",
    "Butterfly", "Cameo", "Candy", "Carrot", "Cinnamon", "Cloud",
    "Clover", "Coral", "Cricket", "Crystal", "Cupcake", "Dew",
    "Diva", "Doodle", "Dot", "Dream", "Duchess", "Dusty", "Elf",
    "Feather", "Flicker", "Fluffy", "Foxy", "Fudge", "Garnet",
    "Ginger", "Glitter", "Goldie", "Gracie", "Honey", "Icy",
    "Iris", "Ivory", "Jellybean", "Jewel", "Karma", "Kiki",
    "Lavender", "Lemon", "Lilac", "Lily", "Lollipop", "Love",
    "Lulu", "Mango", "Marmalade", "Marshmallow", "Meadow",
    "Mermaid", "Merry", "Mint", "Misty", "Mocha", "Muffin",
    "Munchkin", "Nectar", "Nibbles", "Nutmeg", "Olive", "Opal",
    "Pansy", "Peach", "Peanut", "Pearl", "Petal", "Pixie",
    "Plum", "Poppy", "Primrose", "Pumpkin", "Rain", "Rainbow",
    "Raven", "Ribbons", "Rose", "Ruby", "Saffron", "Sapphire",
    "Shadow", "Shimmer", "Snow", "Snowflake", "Sparrow", "Spirit",
    "Sprinkle", "Star", "Starlight", "Stitch", "Sugar", "Sunny",
    "Sunshine", "Sweetie", "Taffy", "Thistle", "Tinker", "Topaz",
    "Trinket", "Tulip", "Velvet", "Violet", "Whiskers", "Whisper",
    "Wiggles", "Wink", "Winter", "Wisp", "Yara", "Zinnia"
];
